### ISSUE TITLE
Select media link does not seem to work always

### ISSUE THREAD

**Issue by Andrei-** [rasmusjp/umbraco-multi-url-picker#69]
Hi Rasmus,
I think I hit a small bug in the picker. We have version 2.1 installed in umbraco 7.7.6. When you try to select from media library and find a file via search, the Url field doesn't get populated. However if you select be clicking through folders it works

**Comment by wally666** [comment]
I confirm! This is a bug. 
The package does not work if you use searching.

**Comment by leekelleher** [comment]
I tried to reproduce this with Umbraco v7.12.3 (MultiUrlPicker v2.2.0), but it works as expected. I assume this was resolved in recent Umbraco versions.

**Comment by shearer3000** [comment]
Confirming this is still an issue on umbraco 7.12.4 and RJP.UmbracoMultiUrlPicker 2.2.0

The issue only occurs when using the search, its not an issue when using the tree.
